import Navbar from "@/components/Navbar/Navbar";
import { Work_Sans } from "next/font/google";
import "./globals.css";

const workSans = Work_Sans({ subsets: ["latin"] });

export const metadata = {
  title: "Ilan Fritzler - Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {

  return (
    <html lang="en">
      <body className={workSans.className}>
        <Navbar />
        <main className="flex flex-1 flex-col justify-start px-36 mt-32 gap-12">
          {children}
        </main>
      </body>
    </html>
  );
}
